-- Intentionally empty. The tester-code unlock was removed because digital
-- Premium access must be granted through store-managed purchase mechanisms.
-- The filename remains in migration history so previously linked databases
-- keep a consistent migration sequence.
